import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { Candle, PaperTrade, Signal, Timeframe } from "@/types";
import { settleTrades, tradeFromSignal } from "@/lib/analytics/tradeTracker";

interface AnalyticsState {
  trades: PaperTrade[];
  /** Track a new signal as an open paper trade (deduped by signalId). */
  trackSignal: (signal: Signal) => void;
  /** Settle open trades for a symbol+timeframe against fresh candles. */
  settle: (candles: Candle[], symbol: string, timeframe: Timeframe) => void;
  reset: () => void;
}

/**
 * Live paper-trading ledger. Signals generated by the strategy are recorded
 * here and settled against streaming candles so the Analytics view can show
 * real, evolving performance without any broker connection.
 */
export const useAnalyticsStore = create<AnalyticsState>()(
  persist(
    (set, get) => ({
      trades: [],
      trackSignal: (signal) => {
        if (get().trades.some((t) => t.signalId === signal.id)) return;
        set((s) => ({ trades: [tradeFromSignal(signal), ...s.trades].slice(0, 500) }));
      },
      settle: (candles, symbol, timeframe) => {
        if (!candles.length) return;
        set((s) => {
          const next = settleTrades(s.trades, candles, symbol, timeframe);
          // Only update state if something actually changed (avoid re-renders).
          const changed = next.some((t, i) => t !== s.trades[i]);
          return changed ? { trades: next } : s;
        });
      },
      reset: () => set({ trades: [] }),
    }),
    { name: "ict-analytics" },
  ),
);
